.TH "speedreed" "1" "(Copyright) November, 2021" "speedreed v1.0" ""
.hy
.SH NAME
.PP
speedreed \- concatenate files and print on the standard output
(quickly, with style)
.SH SYNOPSIS
.PP
\f[B]speedreed\f[R] [\f[I]FILE\f[R]]\&... \f[B]speedreed\f[R]
[\f[I]OPTION\f[R]]\&...
.SH DESCRIPTION
.PP
Concatenate FILE(s), or standard input, to standard output.
.PP
With no FILE, or when FILE is \-, read standard input (quickly, with
style).
.PP
\f[B]\-t\f[R] \f[B]\[en]time\f[R] Set delay between chars, (default .01)
.PP
\f[B]\-R\f[R] \f[B]\[en]reverse\f[R] Reverse the given standard input or
file contents
.PP
\f[B]\-V\f[R] \f[B]\[en]version\f[R] Print version and exit
.PP
\f[B]\-h\f[R] \f[B]\[en]help\f[R] Show this help message and exit
.SH EXAMPLES
.TP
.B \f[B]speedreed\f[R]
Await input from standard in
.TP
.B \f[B]fortune | speedreed | lolcat\f[R]
Read a colorful cookie very quickly! (or slowly)
.TP
.B \f[B]ls | speedreed\f[R]
Read out files in your system with style
.SH COPYRIGHT
.PP
Copyright (C) 2021 Xander Tedder.
License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH AUTHORS
Xander Tedder (xandertedder7\[at]gmail.com).
